EVALUATE
VAR detail_sales_per_zip_state = SELECTCOLUMNS( ADDCOLUMNS (CALCULATETABLE(
                            catalog_sales,
                            date_dim[d_qoy] = 1,
                            date_dim[d_year] = 2001,
                            USERELATIONSHIP ( catalog_sales[cs_bill_customer_sk], customer[c_customer_sk] ),
                            USERELATIONSHIP ( customer[c_current_addr_sk], customer_address[ca_address_sk] ),
                            USERELATIONSHIP ( catalog_sales[cs_sold_date_sk], date_dim[d_date_sk] )
                        ),
                "ca_zip", RELATED ('customer_address'[ca_zip]),
                "ca_state", RELATED ('customer_address'[ca_state])),
                [cs_sales_price], [ca_zip], [ca_state])
                
VAR filtered_detail_sales_per_zip_state = FILTER(detail_sales_per_zip_state,
                OR( OR( LEFT ( [ca_zip], 5 ) IN {"85669", "86197", "88274", "83405", "86475", "85392", "85460", "80348", "81792"},
                          [ca_state] IN {"CA", "WA", "GA"}),
                        [cs_sales_price] > 500) )
                      

VAR sales_per_zip_state = GROUPBY(filtered_detail_sales_per_zip_state,
                                    [ca_zip], "total_sales_price", SUMX(CURRENTGROUP(), [cs_sales_price]))

RETURN TOPN(100, sales_per_zip_state, [ca_zip])
